'''
Create a program that will play the “cows and bulls” game with the user. 
The game works like this:

Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. 
For every digit that the user guessed correctly in the correct place, they have a “cow”. 
For every digit the user guessed correctly in the wrong place is a “bull.” 
Every time the user makes a guess, tell them how many “cows” and “bulls” they have. 
Once the user guesses the correct number, the game is over. 
Keep track of the number of guesses the user makes throughout teh game and tell the user at the end.

Say the number generated by the computer is 1038. 
An example interaction could look like this:

  Welcome to the Cows and Bulls Game! 
  Enter a number: 
  >>> 1234
  2 cows, 0 bulls
  >>> 1256
  1 cow, 0 bulls
  ...

Until the user guesses the number.
'''

import random

def create_random_number(digits = 4):
    return ''.join([str(random.randint(0, 9)) for _ in range(digits)])

def get_prediction(help_text="Enter your 4 digit number prediction: "):
    return input(help_text)

def get_cows(number, prediction):
    cows = 0
    aux_number = []
    aux_prediction = []

    for i in range(len(number)):
        if number[i] == prediction[i]:
            cows += 1
        else:
            aux_number.append(number[i])
            aux_prediction.append(prediction[i])
    # print(cows)
    # print(aux_number)
    # print(aux_prediction)

    return cows, aux_number, aux_prediction

def get_bulls(number, prediction):
    bulls = 0
    for pred in prediction:
        if pred in number:
            bulls += 1
            number.pop(number.index(pred))
    
    # print(bulls)
    # print(number)
    # print(prediction)

    return bulls
        
def verify_length(number, prediction):
    if len(number) == len(prediction):
        return True
    else:
        print(f'Your prediction size is different, must be {len(number)+1} digits!')
        return False

def play_game(digits = 4):
    number = create_random_number(digits)
    # print(number)

    status = True
    tries = 0
    guess = []

    while status:
        predict = get_prediction()
        # print(predict)

        length_ok = verify_length(number, predict)
        tries += 1
        guess.append(predict)

        if number == predict:
            print('-' * 80)
            print('Congratulations!!!')
            print(f'You discovered secret number ({number}) within {tries} tries')
            print('These are your tries:')
            for i, tries in enumerate(guess):
                print(f'{i+1} - {tries}')
            break
        else:
            if length_ok:
                cows, num, pred = get_cows(number, predict)
                bulls = get_bulls(num, pred)
                print(f'cows: {cows} | bulls: {bulls}')
            else:
                continue
        
        print(f'This is your try #{tries}')



if __name__ == "__main__":
    play_game()